version: "3"
services:
  agurim:
    image: keiichi/agurim
    build: .
    container_name: agurim
    #environment:
    #  - DATASET_NAMES=dataset1 dataset2
    #  - DEFAULT_DATASET_NAME=dataset1
    ports:
      - 80:80
    volumes:
      - ./datasets:/var/www/datasets
    restart: always
    #logging:
    #  driver: "journald"
